<?php

namespace AppBundle\Repository;

/**
 * Centre_livraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Centre_livraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
